package com.gammaengage.sdk

import org.junit.Assert.assertEquals
import org.junit.Test

/** Expected values below were generated by Node (JSON.stringify + crypto) — the server's own primitives. */
class EventSignerTest {

    @Test
    fun plain_body_and_signature_match_node() {
        val player = "player-123"
        val body = EventSigner.buildBody(
            eventType = "push_token_registered",
            brandId = "brand-1",
            playerId = player,
            payload = listOf("device_token" to "tok:en-_1", "platform" to "android"),
            eventId = "evt-1",
            idempotencyKey = "idem-1",
            occurredAt = "2026-09-30T07:00:00.000Z",
        )
        assertEquals("{\"schema_version\":\"1.0\",\"event_id\":\"evt-1\",\"event_type\":\"push_token_registered\",\"brand_id\":\"brand-1\",\"source_system\":\"android-sdk\",\"occurred_at\":\"2026-09-30T07:00:00.000Z\",\"player_ref\":{\"external_player_id\":\"player-123\"},\"payload\":{\"device_token\":\"tok:en-_1\",\"platform\":\"android\"},\"idempotency_key\":\"idem-1\"}", body)
        assertEquals("93348af4735ed42979da62d3567ee2b733862bdf0acba31d493dfa1ebfecbefa", EventSigner.hmacHex("s3cret", body))
    }

    @Test
    fun tricky_body_and_signature_match_node() {
        val player = "pl/ay\"er\\1\u000a\u0001\u00e9\ud83d\ude00\ud800x"
        val body = EventSigner.buildBody(
            eventType = "push_token_registered",
            brandId = "brand-1",
            playerId = player,
            payload = listOf("device_token" to "tok:en-_1", "platform" to "android"),
            eventId = "evt-1",
            idempotencyKey = "idem-1",
            occurredAt = "2026-09-30T07:00:00.000Z",
        )
        assertEquals("{\"schema_version\":\"1.0\",\"event_id\":\"evt-1\",\"event_type\":\"push_token_registered\",\"brand_id\":\"brand-1\",\"source_system\":\"android-sdk\",\"occurred_at\":\"2026-09-30T07:00:00.000Z\",\"player_ref\":{\"external_player_id\":\"pl/ay\\\"er\\\\1\\n\\u0001\u00e9\ud83d\ude00\\ud800x\"},\"payload\":{\"device_token\":\"tok:en-_1\",\"platform\":\"android\"},\"idempotency_key\":\"idem-1\"}", body)
        assertEquals("1b521caf2fea34be01d1163825832e8e6c43123292e70570404fe7785e5d4c17", EventSigner.hmacHex("s3cret", body))
    }
}
